language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --dev

script:
  - vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - vendor/bin/phpunit tests/
  - vendor/bin/phpcs --standard=PSR2 ./src/

after_script:
  - php vendor/bin/coveralls -v